// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pexeso.Models;

namespace Pexeso.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200120115935_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Pexeso.Models.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Id_pair");

                    b.Property<int>("PoleId");

                    b.Property<bool>("Revealed");

                    b.HasKey("Id");

                    b.HasIndex("PoleId");

                    b.ToTable("Cards");

                    b.HasData(
                        new { Id = 1, Id_pair = 2, PoleId = 1, Revealed = false },
                        new { Id = 2, Id_pair = 1, PoleId = 1, Revealed = false },
                        new { Id = 3, Id_pair = 4, PoleId = 1, Revealed = false },
                        new { Id = 4, Id_pair = 3, PoleId = 1, Revealed = false },
                        new { Id = 5, Id_pair = 6, PoleId = 1, Revealed = false },
                        new { Id = 6, Id_pair = 5, PoleId = 1, Revealed = false },
                        new { Id = 7, Id_pair = 8, PoleId = 1, Revealed = false },
                        new { Id = 8, Id_pair = 7, PoleId = 1, Revealed = false },
                        new { Id = 9, Id_pair = 10, PoleId = 1, Revealed = false },
                        new { Id = 10, Id_pair = 9, PoleId = 1, Revealed = false },
                        new { Id = 11, Id_pair = 12, PoleId = 1, Revealed = false },
                        new { Id = 12, Id_pair = 11, PoleId = 1, Revealed = false },
                        new { Id = 13, Id_pair = 14, PoleId = 1, Revealed = false },
                        new { Id = 14, Id_pair = 13, PoleId = 1, Revealed = false },
                        new { Id = 15, Id_pair = 16, PoleId = 1, Revealed = false },
                        new { Id = 16, Id_pair = 15, PoleId = 1, Revealed = false }
                    );
                });

            modelBuilder.Entity("Pexeso.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("src")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Imgs");

                    b.HasData(
                        new { Id = 1, src = "~/images/1.jpg" },
                        new { Id = 2, src = "~/images/2.jpg" },
                        new { Id = 3, src = "~/images/3.jpg" },
                        new { Id = 4, src = "~/images/4.jpg" },
                        new { Id = 5, src = "~/images/5.jpg" },
                        new { Id = 6, src = "~/images/6.jpg" },
                        new { Id = 7, src = "~/images/7.jpg" },
                        new { Id = 8, src = "~/images/8.jpg" },
                        new { Id = 9, src = "~/images/1.jpg" },
                        new { Id = 10, src = "~/images/2.jpg" },
                        new { Id = 11, src = "~/images/3.jpg" },
                        new { Id = 12, src = "~/images/4.jpg" },
                        new { Id = 13, src = "~/images/5.jpg" },
                        new { Id = 14, src = "~/images/6.jpg" },
                        new { Id = 15, src = "~/images/7.jpg" },
                        new { Id = 16, src = "~/images/8.jpg" }
                    );
                });

            modelBuilder.Entity("Pexeso.Models.Pole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("score");

                    b.Property<int>("temp1");

                    b.Property<int>("temp2");

                    b.HasKey("Id");

                    b.ToTable("Pole");

                    b.HasData(
                        new { Id = 1, score = 0, temp1 = 0, temp2 = 0 }
                    );
                });

            modelBuilder.Entity("Pexeso.Models.Card", b =>
                {
                    b.HasOne("Pexeso.Models.Pole", "Pole")
                        .WithMany("CardList")
                        .HasForeignKey("PoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
